### ISSUE TITLE
License

### ISSUE THREAD

**Issue by heinezen** [e00E/Age-of-Empires-II-Grid-Generator#1]
Does this project has a license or do you intend to add one?

I'm asking because it might be nice to add this script to [here](https://github.com/SFTtech/openage-modding) :)

**Comment by e00E** [comment]
Thank you for reminding me. I have added the GPL.

I am totally fine with including the script there.

**Comment by heinezen** [comment]
Great! Do you want to add it there yourself? I don't necessarily want to "steal" your credit :smile:

**Comment by e00E** [comment]
Don't worry, just add it.
